// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRVJVkoDtIJgNGCunx0VqunC-9B6h6GHM',
    appId: '1:447137263961:web:5f19185f87acedae2c9c48',
    messagingSenderId: '447137263961',
    projectId: 'al-fajr-1d0f5',
    authDomain: 'al-fajr-1d0f5.firebaseapp.com',
    storageBucket: 'al-fajr-1d0f5.firebasestorage.app',
    measurementId: 'G-2TV4K5GSDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHkYBgt_tX4zwelwa5c3DSRr8mRs1UQII',
    appId: '1:447137263961:android:dfff0fa0afad1fb52c9c48',
    messagingSenderId: '447137263961',
    projectId: 'al-fajr-1d0f5',
    storageBucket: 'al-fajr-1d0f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_uFaknrckvVmEH6hN0gNOAzCfQdgqA8',
    appId: '1:447137263961:ios:80355deec8161fa72c9c48',
    messagingSenderId: '447137263961',
    projectId: 'al-fajr-1d0f5',
    storageBucket: 'al-fajr-1d0f5.firebasestorage.app',
    iosBundleId: 'com.example.alFajr',
  );
}
