class SurahData {
  static const Map<int, String> malayNames = {
    1: "Pembukaan", 2: "Lembu Betina", 3: "Keluarga Imran", 4: "Wanita", 
    5: "Hidangan", 6: "Binatang Ternakan", 7: "Tempat Tertinggi", 8: "Rampasan Perang", 
    9: "Taubat", 10: "Nabi Yunus", 11: "Nabi Hud", 12: "Nabi Yusuf", 
    13: "Guruh", 14: "Nabi Ibrahim", 15: "Al-Hijr", 16: "Lebah", 
    17: "Perjalanan Malam", 18: "Gua", 19: "Maryam", 20: "Ta Ha", 
    21: "Para Nabi", 22: "Haji", 23: "Golongan Beriman", 24: "Cahaya", 
    25: "Pembeda", 26: "Para Penyair", 27: "Semut", 28: "Cerita", 
    29: "Lelabah", 30: "Bangsa Rom", 31: "Luqman", 32: "Sujud", 
    33: "Golongan Bersekutu", 34: "Kaum Saba'", 35: "Pencipta", 36: "Ya Sin", 
    37: "Yang Berbaris", 38: "Saad", 39: "Kumpulan", 40: "Pengampun", 
    41: "Dijelaskan", 42: "Mesyuarat", 43: "Perhiasan Emas", 44: "Kabut", 
    45: "Yang Berlutut", 46: "Bukit Pasir", 47: "Nabi Muhammad", 48: "Kemenangan", 
    49: "Bilik-bilik", 50: "Qaaf", 51: "Angin yang Menerbangkan", 52: "Bukit", 
    53: "Bintang", 54: "Bulan", 55: "Yang Maha Pemurah", 56: "Peristiwa Besar", 
    57: "Besi", 58: "Wanita yang Merayu", 59: "Pengusiran", 60: "Wanita yang Diuji", 
    61: "Barisan", 62: "Hari Jumaat", 63: "Golongan Munafik", 64: "Saling Menipu", 
    65: "Talak", 66: "Mengharamkan", 67: "Kerajaan", 68: "Pena", 
    69: "Kenyataan yang Benar", 70: "Tempat Mendaki", 71: "Nabi Nuh", 72: "Jin", 
    73: "Yang Berselimut", 74: "Yang Berkemul", 75: "Hari Kiamat", 76: "Manusia", 
    77: "Malaikat yang Diutus", 78: "Berita Besar", 79: "Malaikat yang Mencabut", 80: "Bermuka Masam", 
    81: "Menggulung", 82: "Terbelah", 83: "Golongan yang Curang", 84: "Terbelah Dua", 
    85: "Gugusan Bintang", 86: "Bintang yang Datang Malam", 87: "Yang Maha Tinggi", 88: "Peristiwa yang Menyelubungi", 
    89: "Fajar", 90: "Negeri", 91: "Matahari", 92: "Malam", 
    93: "Waktu Dhuha", 94: "Melapangkan Dada", 95: "Buah Tin", 96: "Segumpal Darah", 
    97: "Kemuliaan", 98: "Bukti yang Nyata", 99: "Goncangan", 100: "Kuda yang Berlari Kencang", 
    101: "Hari yang Riuh", 102: "Bermegah-megahan", 103: "Masa", 104: "Pengumpat", 
    105: "Gajah", 106: "Quraisy", 107: "Barangan Berguna", 108: "Nikmat yang Banyak", 
    109: "Golongan Kafir", 110: "Pertolongan", 111: "Tali yang Gegetas", 112: "Ikhlas", 
    113: "Waktu Subuh", 114: "Manusia",
  };
}